### PR TITLE
fixed many syntax errors and fixed crash

### PR DESCRIPTION
**Pull request by AmiroEmad**
Fixed all errors just do the plugin.yml commands thing and it will work

### CODE REVIEW

**Comment by AmiroEmad** [comment]
i am sure you have more problems in the plugin but what i did is just fix the plugin load but i didn't look into the commands yet

**Comment by Dog2puppy** [comment]
Still somthing wrong when Travis builds it.

**Comment by Dog2puppy** [comment]
@AmiroEmad Check https://travis-ci.org/Dog2puppy/ServerCore/builds/142015495#L707

**Comment by Dog2puppy** [comment]
Approved. Gonna merge it.

**Comment by Dog2puppy** [comment]
Travis was able to build it. Thats good.

**Comment by Dog2puppy** [comment]
But it still says it failed.

**Comment by Dog2puppy** [comment]
I think somthing needs changed with my build script.

**Comment by AmiroEmad** [comment]
i think it fails because imagicalmine have a bug that make it crash so i suggest that we ask @keithkfng to rebuild his script so his script use pocketmine and pocketmine dev tools instead

**Comment by Dog2puppy** [comment]
@AmiroEmad What build script do you use?

**Comment by Dog2puppy** [comment]
@AmiroEmad Still there?

**Comment by Dog2puppy** [comment]
...

**Comment by AmiroEmad** [comment]
@Dog2puppy yes i am still here

**Comment by Dog2puppy** [comment]
What build script do you use? @AmiroEmad

**Pull request merged**
